### ISSUE TITLE
tar balls published on github should use sane directory names

### ISSUE THREAD

**Issue by letoams** [letoams/hash-slinger#27]
For uploading to distributions like fedora, centos, we need a proper versioned tar ball. I used to create those outside of github. Now with github we have two bad choices:

- a link that points to a file called v<VERSION>.tar.gz which does contain the right name-version/ prefix
- a link to a shortcommit version that has the right name, hash-slinger-<VERSION>.tar.gz but untar's into a directory with the tag commit id

Both are wrong :(

Is there a way to generate proper release tar balls on github? The documentation didn't seem to think so. If not, perhaps I should go back to using https://nohats.ca/ftp/hash-slinger/ as the official download site.

**Comment by stoecker** [comment]
That's a common problem. For open build service we workaround this with a special URL:

`https://github.com/letoams/%{name}/archive/%{version}.tar.gz#/%{name}-%{version}.tar.gz`

see https://build.opensuse.org/package/view_file/server:dns/hash-slinger/hash-slinger.spec?expand=1

This downloads the right file with the correct name. Otherwise you can simply add a manual made file to a release which has the correct name and is e.g. compressed with ".xz" (so no need to use another download place), but that's additional handwork.

**Comment by stoecker** [comment]
Note that the save file name for the download in the browser is correct. This issue happens only with download tools which ignore the file name of the download and use the URL part and for these the workaround works in most cases.
